# Generated by Django 4.2 on 2023-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('parentName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('partName', models.CharField(max_length=20)),
                ('partAge', models.IntegerField()),
                ('partGrade', models.IntegerField()),
                ('program', models.CharField(max_length=25)),
                ('status', models.BooleanField()),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
