# Generated by Django 4.2 on 2023-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campapplications',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='partAge',
            new_name='CamperAge',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='partGrade',
            new_name='CamperGrade',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='parentName',
            new_name='CamperName',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='creationTime',
            new_name='CreationTime',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='partName',
            new_name='ParentName',
        ),
        migrations.RenameField(
            model_name='campapplications',
            old_name='phoneNumber',
            new_name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='campapplications',
            name='program',
        ),
        migrations.RemoveField(
            model_name='campapplications',
            name='status',
        ),
        migrations.AddField(
            model_name='campapplications',
            name='Program',
            field=models.CharField(choices=[('Bio', 'Biophysical'), ('Robotics', 'Robotics'), ('Cyber', 'Cyber Security'), ('Cryptography', 'Cryptography')], default='Biophysical', max_length=25),
        ),
        migrations.AddField(
            model_name='campapplications',
            name='Status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
