# Generated by Django 4.2 on 2023-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_address_campapplications_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campapplications',
            name='Status',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
