# Generated by Django 4.2 on 2023-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_campapplications_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campapplications',
            name='Status',
        ),
        migrations.AddField(
            model_name='campapplications',
            name='regstatus',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Paid', 'Paid'), ('Waiting List', 'Waiting List')], default='Waiting List', max_length=20),
        ),
        migrations.AlterField(
            model_name='campapplications',
            name='CamperGrade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='campapplications',
            name='Program',
            field=models.CharField(choices=[('Biophysical', 'Biophysical'), ('Robotics', 'Robotics'), ('Cyber Security', 'Cyber Security'), ('Cryptography', 'Cryptography')], default='Biophysical', max_length=25),
        ),
    ]
